### PR TITLE
Misc updates: global require, Ctrl-c + SIGINT

### LINKED ISSUE #90: Error: Cannot find module 'nodejs-dashboard'
mac OS 10.13.3
node v 8.9.1
Tried on Hyper and iTerm
```
npm install -g nodejs-dashboard
nodejs-dashboard -- node -r nodejs-dashboard test.js
```

This starts the dashboard but gives me an error accessing the module...

screen shot 2018-03-29 at 14 06 53

### PR DESCRIPTION
**Pull request by ryan-roemer**
- Add the `node_modules` directory from wherever `nodejs-dashboard` is installed to `NODE_PATH` so that the portion of the instructions `<SNIPPED> -- node -r nodejs-dashboard <SNIPPED>` works. Appreciate review from @AaronRobinson and @carbonrobot ! Fixes #90 
- Use SIGINT for Ctrl-c. Replaces and closes #93 Thanks for the original PR and appreciate review @joakimbeng

### CODE REVIEW

File: lib/dashboard.js [hunk 1]
```diff
@@ -52,7 +52,7 @@ Dashboard.prototype._configureKeys = function () {
   // this key will be watched on the global screen
   this.screen.ignoreLocked = ["C-c"];
   this.screen.key("C-c", () => {
-    process.exit(0); // eslint-disable-line no-process-exit
+    process.kill(process.pid, "SIGINT");
```
Comment (parkerziegler) [inline lib/dashboard.js]: Yep this looks right! The only thing we did different in `webpack-dashboard` was listen for `"escape"` and `"q"` as valid keys to trigger sending `SIGINT`. We could consider doing that here as well.

Comment (ryan-roemer) [reply lib/dashboard.js]: Good idea! Added https://github.com/FormidableLabs/nodejs-dashboard/issues/106 to allow some discussion first.

**Comment by ryan-roemer** [comment]
Released in `nodejs-dashboard@0.5.1`
